### ISSUE TITLE
Use Cases

### ISSUE THREAD

**Issue by dancesWithCycles** [entur/anshar#52]
Hi folks,
Thank you so much for providing and maintaining this repository. I am happy to announce that I am operating a test instance that successfully interacts with Entur's CEN SIRI services.

![Screenshot_2022-09-15_13-36-47](https://user-images.githubusercontent.com/47819327/190398314-d630cb94-5a1c-43b5-88ce-df242ba801f5.png)

To move a step forward I am wondering about the use cases of this repository. The following is my understanding so far. Is that correct?

* According to the [readme](https://github.com/entur/anshar/blob/master/README.md) Anshar is a SIRI hub.
* Subscribed SIRI services (inbound) are forwarded to subscribed clients (outbound).
* Incoming XML from SIRI services are validated against the SIRI XSD.

The following URL's from the [readme](https://github.com/entur/anshar/blob/master/README.md) seem to have issues. Are they still up to date?
```
http://<host>:<port>/up
http://<host>:<port>/ready
http://<host>:<port>/healthy
```

Can you imagine a reason why I see in the admin-gui a warning triangle and no processed objects for the ET and SX service but not for the SIRI VM service?

![Screenshot_2022-09-15_14-13-23](https://user-images.githubusercontent.com/47819327/190401634-8b149caa-6c0b-44a6-8503-3031ed76db2b.png)

Cheers!

**Comment by lassetyr** [comment]
1. Your understanding is correct
2. The health-endpoints are up to date, but they do not provide any HTML-data - just a simple "OK" to allow deployment-services (like e.g. kubernetes) can verify that service is ready.
```
⇒  curl http://localhost:8012/up  
OK%                                                                                                                                                                                                                                                       
⇒  curl http://localhost:8012/ready                                                                                                                                                          
OK%                                                                                                                                                                                                           
⇒  curl http://localhost:8012/healthy                                                                                                                                                       
OK%                                                                                                                                                                                                           
```
3. The warning-triangle is an indication that the subscription is not receiving any data - as shown in a tooltip when hovering over it.
![image](https://user-images.githubusercontent.com/73600/190411765-75f05f9e-3113-40cb-ac3b-13d84f49a798.png)

**Comment by dancesWithCycles** [comment]
Cheers mate!
